version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: nestblog-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestblog
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ldap:
    build:
      context: ./ldap
    container_name: nestblog-ldap
    environment:
      LDAP_ORGANISATION: "NestBlog"
      LDAP_DOMAIN: "nestblog.local"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      LDAP_TLS: "false"
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: nestblog-keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - ldap



volumes:
  postgres_data:
  ldap_data:
  ldap_config:
