version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: nestblog-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestblog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
